services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8082:8081"
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms1g
        -Xmx1g
        -XX:MaxDirectMemorySize=1g
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data:
    name: nexus-data