apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:24.0.9-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-storage
      mountPath: /var/lib/docker
  - name: shell
    image: docker:24-cli
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    command:
    - sleep
    args:
    - "9999999"
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  - name: kubectl
    image: bitnami/kubectl:latest
    securityContext:
      runAsUser: 0
    command:
    - sleep
    args:
    - "9999999"
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: docker-storage
    emptyDir: {}
  - name: workspace-volume
    emptyDir: {}